### ISSUE TITLE
 SwiftSyntax parser library isn't compatible

### ISSUE THREAD

**Issue by Fritoo** [vinivendra/Gryphon#101]
**Describe the bug**
SwiftSyntax parser library isn't compatible

**Your environment (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Gryphon version: 0.10.6

**Screenshots and code snippets**
![image](https://user-images.githubusercontent.com/1719209/108541075-e35b3b80-7296-11eb-951e-07f150e34c63.png)
![image](https://user-images.githubusercontent.com/1719209/108541120-f110c100-7296-11eb-8764-440202b7c405.png)

**Bonus: Gryphon's verbose output**
The `--verbose` option makes Gryphon print a lot of information that may help the maintainers find out what went wrong.
- If the bug happened while running Gryphon from the command line, you can try running it again with the `--verbose` option and including the output in your report.
- If you're running Gryphon from Xcode, this output can be found by pressing **⌘+9** and selecting the topmost "build" report under the Gryphon target:
	![Where to find the verbose output on Xcode](https://vinivendra.github.io/Gryphon/assets/images/other/verboseExample.png)

**Comment by vinivendra** [comment]
Hi, thanks for reporting this bug :)

It seems that you're using Gryphon with Swift 5.2, but your app uses the Swift 5.3 toolchain. This might be fixed by updating Gryphon, since newer versions don't use toolchains anymore. Can you try updating to Gryphon v0.13.1 and letting me know if it works?

**Comment by Fritoo** [comment]
@vinivendra That did it, thanks!
