### ISSUE TITLE
SwiftUI to Jetpack Compose translation

### ISSUE THREAD

**Issue by troys-code** [vinivendra/Gryphon#107]
When working on a mobile app, the user interface must be created twice, or created once in a non-native language.

Now that:

- SwiftUI is stable
- Jetpack Compose is in version 1.0 beta

It seems like a prime time to consider SwiftUI to Jetpack Compose translation.
Would be curious to know if this is even possible? I would make use of such a tool if it can work well.

### Jetpack Compose

Overview: https://developer.android.com/jetpack/compose

![](https://developer.android.com/images/jetpack/compose/landing-code-static.svg)

### SwiftUI

Overview: https://developer.apple.com/xcode/swiftui/

![](https://developer.apple.com/xcode/swiftui/images/example-syntax-dark-large.jpg)

**Comment by troys-code** [comment]
updated description.

@vinivendra what do you think?

**Comment by vinivendra** [comment]
Hi Troy, thanks for the suggestion. This seems like it would be a really good thing to support, but also like something very complicated. We'd have to take a very deep look at how both libraries work to see if a translation is possible. For example:

- It's important to look into how to mitigate differences between similar components (e.g. in what situations does SwiftUI's Text behave differently than Jetpack Compose's Text?);
- We'd have to watch for pitfalls with the different binding systems (e.g. SwiftUI's `@ObservableObject`s vs. Jetpack Compose's bindings, etc);
- And I expect we'd have to write *a lot* of library code (i.e. extensions to Swift and Kotlin like Gryphon's List/Map classes).

Now that Gryphon isn't my full time job anymore, this doesn't seem like something I'd have the time to do well. That said, if you have experience with these technologies and would like to try it out, feel free to contribute! I'm willing to help in any way I can.
