### ISSUE TITLE
Swift 5.5 support

### ISSUE THREAD

**Issue by bardigolriz** [vinivendra/Gryphon#110]
I’m currently on Xcode 13 beta using the Swift 5.5 toolchain. This isn’t supported by Gryphon at the moment, but with iOS 15’s public release imminent, it would be great for Gryphon to support the latest Swift version for those of us who are depending on it already.

I was asked to create this issue, so that progress on this task can be shared.

Many thanks!

**Comment by vinivendra** [comment]
Hi there, thanks for bringing this to my attention. It took a while, but I was able to create a version that should support Swift 5.5 (at least the current beta). It's on the development branch currently, you can test it with `brew install vinivendra/gryphon/gryphon --HEAD`.

If there are no problems, I'll release it as soon as Swift 5.5 is officially released, ok?

**Comment by vinivendra** [comment]
Swift 5.5 support was released in version 0.18.
