### ISSUE TITLE
GryphonSwiftLibrary fails to build on Xcode 13

### ISSUE THREAD

**Issue by tfmart** [vinivendra/Gryphon#111]
**Describe the bug**
When I try to build a project which contains the `GryphonSwiftLibrary` file, the file fails to build on Xcode 13.0/13.1. I've already tried updating the file by running `gryphon generate-libraries` after updating to `0.18` but it still fails. I've tried using it in both a existing project, which works fine on Xcode 12, and on a brand new project created with Xcode 13. In both cases, Xcode return build errors on the list types `_ListSlice`, `List`, `MutableList` and `Map`

**How to reproduce it**
How can someone else make this bug happen in their computer?
1. Add the GryphonSwiftLibrary to a Xcode project with `gryphon generate-libraries`
2. Attempt to build the project on Xcode 13.0 or later
3. The build fails, returning the errors listed on the screenshots below

**Your environment (please complete the following information):**
 - OS: macOS 11.4
 - Gryphon version: 0.18

**Screenshots and code snippets**
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/23082132/139284527-191ef36a-a08e-4054-8daa-d4875a867fb7.png">
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/23082132/139284559-35b6585c-a70f-4d4d-8fdf-3487a94e32ef.png">
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/23082132/139284582-97623fe6-52bb-426c-9d2c-b2af88c8cd47.png">
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/23082132/139284597-37d0a7d3-38d1-4066-985c-c03a76bbc63e.png">

**Comment by vinivendra** [comment]
Hey @tfmart, thank you for opening this bug. I was already trying to solve it, but it's good to have a GitHub issue so we can track the progress.

It seems that there was some change in the way Swift interprets protocol conformances that breaks the implementations of the classes. I'm not yet sure what happened, and the error messages aren't helping. I might have to ask for help in the Swift forums.

In the meantime, if you make any changes to the library file that makes it work, be sure to let me know, OK?

**Comment by tfmart** [comment]
Sure @vinivendra, thanks for reaching out!

**Comment by vinivendra** [comment]
I tried again today, but no luck. I just posted this question on the Swift forums, so I hope someone there can help: https://forums.swift.org/t/protocol-conformance-stopped-working-in-xcode-13/53345

**Comment by tfmart** [comment]
Thanks for the update, sadly I couldn't get anything working on my end as well... Let's hope someone can help us out at the forum 🤞

**Comment by vinivendra** [comment]
Hey @tfmart, the Swift forums came through. I just published the fix in [v0.18.1](https://github.com/vinivendra/Gryphon/releases/tag/v0.18.1). Let me know if the problem is fixed, ok?

**Comment by tfmart** [comment]
Glad to hear that, @vinivendra! I'll let you know as soon as I give it a try

**Comment by tfmart** [comment]
Everything is working great so far on my project, @vinivendra, so I'll close this issue. Thanks for the support!
