### ISSUE TITLE
Support Swift 5.6

### ISSUE THREAD

**Issue by vinivendra** [vinivendra/Gryphon#116]
Gryphon should be updated to support Swift 5.6. Here's how it'll probably go:

1. Update the `Package.swift` file to support the [new Swift 5.6 tag](https://github.com/apple/swift-syntax).
2. Update the `SwiftSyntax_PrintableAsTree.swift` file with any nodes that may have been added to Swift 5.6.
3. Test everything to make sure nothing was broken in the process.

Bonus: also update SourceKitten.

**Comment by pgneri** [comment]
Hi o/
Do you have any plans to release a new version?

**Comment by vinivendra** [comment]
Hi! Yes, I do. I’ve been working on this on and off for the last few months, but it’s been much more challenging than I initially thought (and much worse than what was needed for Swift 5.3-5.5).
I think I’m almost there, there are only a few tests left to fix (mainly for Xcode 13.3 integration). However, since I only do this when I have free time (and some mental energy), it’s hard to say when that will be done.
In the meantime, thanks for your patience (and for you question)!

**Comment by pgneri** [comment]
Got it, if I can help in any way, just say so. I even wanted to learn how to maintain the Gryphon, it makes our work and sharing code between platforms a lot easier, you did and you're doing an amazing job!!!

**Comment by vinivendra** [comment]
@pgneri thanks for your support 😄

I just released version `0.19` with support for Swift 5.6. It still doesn't support all features in Xcode 13.3+, but at least it compiles fine now. I'm going to close this issue and open a new one to track Xcode integration separately, ok?

If you want to contribute with the code, all help is welcome! I'd recommend looking at the [good first issues](https://github.com/vinivendra/Gryphon/labels/good%20first%20issue) or picking/opening an issue that you want to see fixed. I also wrote a [contributor's guide](https://vinivendra.github.io/Gryphon/contributing.html) a while ago that might give you some useful information. If you need any help just let me know, I'm more than willing to do whatever I can.
