### ISSUE TITLE
Error installing Gryphon on maOS 12.2.1 (Monterey)

### ISSUE THREAD

**Issue by msegced** [vinivendra/Gryphon#118]
**Describe the bug**
When I install Gryphon with home-brew and manually I always get:
error: the library 'GryphonLib' requires macos 10.13, but depends on the product 'SourceKittenFramework' which requires macos 12.0; consider changing the library 'GryphonLib' to require macos 12.0 or later, or the product 'SourceKittenFramework' to require macos 10.13 or earlier.

**How to reproduce it**
How can someone else make this bug happen in their computer?
1. $ git clone https://github.com/vinivendra/Gryphon.git
2. $ cd Gryphon
3. $ ./Scripts/install.sh

**Your environment (please complete the following information):**
 - OS: macOs 12.2.1
 - Gryphon version: 0.19

Thanks in advance.

**Comment by vinivendra** [comment]
Hi @msegced, thanks for opening this bug report. We might have a solution for it (which is being discussed in #177), I'll let you know if we deploy it so that you can try again.

**Comment by tfmart** [comment]
I've opened #120 to fix this issue

**Comment by Alphapage** [comment]
Hello,
2 months without being able to install the tool !!!
Switch to v12 , swift-tools-version:5.5 and "https://github.com/jpsim/SourceKitten",.exact("0.33.0")
We need to be able to install gryphon

**Comment by pnewell** [comment]
Until they merge it, this will allow you to install:

`mint install tfmart/Gryphon@swift5.7-beta`

**Comment by mlyongardiner** [comment]
Hi, is there no option for Swift 5.7 without Mint?

**Comment by vinivendra** [comment]
Hey folks, we’re concentrating all efforts to support the latest Swift, Xcode and macOS versions to issue #127. If you there’s anything you’d like to contribute, please feel free to join the discussion there.

**Comment by vinivendra** [comment]
Closing this issue as a duplicate, feel free to comment here again if you have any new information that might suggest this is a different problem.
