### ISSUE TITLE
Error installing on a macos 13.1

### ISSUE THREAD

**Issue by Rbaronio** [vinivendra/Gryphon#122]
after using the commands recommended on the tuturial page, i got the following error return:

error: the library 'GryphonLib' requires macos 10.13, but depends on the product 'SourceKittenFramework' which requires macos 12.0; consider changing the library 'GryphonLib' to require macos 12.0 or later, or the product 'SourceKittenFramework' to require macos 10.13 or earlier.

I also had tried the beta released here on the topics: mint install tfmart/Gryphon@swift5.7-beta

**Comment by houmie** [comment]
Same here.

**Comment by ganzogo** [comment]
Same here

**Comment by vinivendra** [comment]
Hey folks, we’re concentrating all efforts to support the latest Swift, Xcode and macOS versions to issue https://github.com/vinivendra/Gryphon/issues/127. If you there’s anything you’d like to contribute, please feel free to join the discussion there.

**Comment by vinivendra** [comment]
Closing this issue as a duplicate, feel free to comment here again if you have any new information that might suggest this is a different problem.
