### ISSUE TITLE
Error install Gryphon

### ISSUE THREAD

**Issue by nicocarry** [vinivendra/Gryphon#123]
hello, when I try to install Gryphon with any method, it gives me the following error:

warning: /Users/Admin/Library/org.swift.swiftpm/configuration is not accessible or not writable, disabling user-level configuration features.
warning: /Users/Admin/Library/org.swift.swiftpm/security is not accessible or not writable, disabling user-level security features.
warning: /Users/Admin/Library/Caches/org.swift.swiftpm is not accessible or not writable, disabling user-level cache features.
error: 'gryphon-0.19': Invalid manifest
/private/tmp/gryphon-20230207-48938-k3bp2b/Gryphon-0.19/Package.swift:23:8: error: no such module 'PackageDescription'
import PackageDescription

What should I do to avoid getting this error?

Thank you

**Comment by vinivendra** [comment]
Hello, we’re concentrating all efforts to support the latest Swift, Xcode and macOS versions to issue https://github.com/vinivendra/Gryphon/issues/127. If you there’s anything you’d like to contribute, please feel free to join the discussion there.

**Comment by vinivendra** [comment]
Closing this issue as a duplicate, feel free to comment here again if you have any new information that might suggest this is a different problem.
