### ISSUE TITLE
Compile C failed

### ISSUE THREAD

**Issue by kwcnldnsldskcls** [vinivendra/Gryphon#124]
**Describe the bug**
Terminal says:
CompileC .../checkouts/GoogleDataTransport/build/GoogleDataTransport.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/client_metrics.nanopb.o 

.../checkouts/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/client_metrics.nanopb.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'GoogleDataTransport' from project 'GoogleDataTransport')
(1 failure)

I looked up the directories and there is no client_metrics.nanopb.o only a client_metrics.nanopb.d 

**How to reproduce it**
"0. installed with mint"
1. just tried to init my .xcodeproj

**Your environment (please complete the following information):**
 - MacOS 13.3
 - Gryphon version: Swift@5.7-beta, Swift 5.7.2 gryphon 0.19

**Comment by vinivendra** [comment]
Hello, we’re concentrating all efforts to support the latest Swift, Xcode and macOS versions to issue https://github.com/vinivendra/Gryphon/issues/127. If you there’s anything you’d like to contribute, please feel free to join the discussion there.

**Comment by vinivendra** [comment]
Closing this issue as a duplicate, feel free to comment here again if you have any new information that might suggest this is a different problem.
