### ISSUE TITLE
Failed to install Gryphon 

### ISSUE THREAD

**Issue by 3llipsisM** [vinivendra/Gryphon#126]
I'm using macOS 13.2.1, Swift version 5.7.2, and Xcode Version 14.2. I get the warning "error: the library 'GryphonLib' requires macos 10.13, but depends on the product 'SourceKittenFramework' which requires macos 12.0; consider changing the library 'GryphonLib' to require macos 12.0 or later, or the product 'SourceKittenFramework' to require macos 10.13 or earlier." the SourceKittenFramework version is 0.34.1

**Comment by scorpio1441** [comment]
I'm getting a similar error using Ventura 13.0, how do I resolve it?

`error: the library 'GryphonLib' requires macos 10.13, but depends on the product 'SourceKittenFramework' which requires macos 12.0; consider changing the library 'GryphonLib' to require macos 12.0 or later, or the product 'SourceKittenFramework' to require macos 10.13 or earlier.
`

**Comment by vinivendra** [comment]
Hey folks, we’re concentrating all efforts to support the latest Swift, Xcode and macOS versions to issue https://github.com/vinivendra/Gryphon/issues/127. If you there’s anything you’d like to contribute, please feel free to join the discussion there.

**Comment by vinivendra** [comment]
Closing this issue as a duplicate, feel free to comment here again if you have any new information that might suggest this is a different problem.
