### ISSUE TITLE
Automatically escape dollar signs

### ISSUE THREAD

**Issue by vinivendra** [vinivendra/Gryphon#3]
Dollar signs ($'s) in Swift strings may cause problems when translated directly, since Kotlin uses them as an escape character. It may be possible to always escape them during the translation, which should fix this problem.

If this gets done, it might be possible to simplify the handling of dollar signs in AuxiliaryFileContents.swift, and maybe other files too.

**Comment by vinivendra** [comment]
This issue is ideal for someone making their first contribution to an open source project. If you have any experience contributing to open source, please let someone else take this one!

I have already implemented a solution locally so that I could make sure it was easy - and so I could write a few instructions:

- [ ] Start by posting a comment below saying you want to work on this (just so that nobody else starts working on it too).
- [ ] Go [here](https://vinivendra.github.io/Gryphon/contributing.html) to learn more about contributing to Gryphon and setting things up. You don't need to understand everything about how the code works, just enough to set up your environment however you prefer it.
- [ ] If you haven't yet, run the tests with `bash runTests.sh -b` to make sure everything is working.
- [ ] Open the `TranspilationPass.swift` file and look for a class called `FixExtensionGenericsTranspilationPass`. Create a new class just below it, and call it something like `EscapeDollarSignsInStringsTranspilationPass`. Make it a subclass of `TranspilationPass` and override the `replaceLiteralStringExpression` function. Put your logic for escaping dollar signs (i.e. turning every `$` into `\$`) inside this function.
- [ ] Add `// gryphon insert:` and `// gryphon annotation:` comments to your new class just like the `FixExtensionGenericsTranspilationPass` class above it.
- [ ] Find where the `FixExtensionGenericsTranspilationPass` class is called in this file's `runSecondRoundOfPasses` method. Add a call to your new class just below it.
- [ ] Run the unit tests with `bash runTests.sh` to make sure everything still works.
- [ ] Add some code to test your changes in the `test.swift` file. You should test at least three or four different cases to make sure everything works. For instance:
	```` swift
	print("$foo")
	print("${foo}")
	
	let bar = "$foo"
	let baz = "\(bar)"
	print(baz)
	````
- [ ] Run your new Gryphon executable to translate the `test.swift` file. Try putting the translation on a new file that you can compile and run to make sure it prints the same things as the original `test.swift` file.
- [ ] Add your new test code to the end of the `Test cases/strings.swift` file; add its translation to the end of the `Test cases/strings.kt` file; then add its output to the end of the `Test cases/strings.output` file.
- [ ] Run the unit tests again (`bash runTests.sh`) to check if your changes to the `.swift` and `.kt` tests files are OK (you might need to fix some whitespace or indentation). Then run the acceptance tests (`bash runTests.sh -a`) to make sure the `.kt` file compiles and the `.output` is OK.
- [ ] Finally, run the bootstrapping tests (`bash runTests.sh -b`) to check if your changes can be translated to Kotlin.
- [ ] Once all these tests are passing, commit the changes you made to all files except the `test.swift` file. Remember to mention issue #3 in your commit message.
- [ ] Push the changes to your fork, then come back to GitHub and create a pull request. Feel free to mention `@vinivendra` to get my attention, and I'll help review the code and merge it.
- [ ] Celebrate! 🎉

**Comment by markkulube** [comment]
@vinivendra - If this is still open, I will on it.

**Comment by vinivendra** [comment]
Yeah, this is still open i anyone wants it :)

**Comment by quinntrang** [comment]
Hi, 

I would like to work on this issue, and this is my first time contributing to open source!

**Comment by vinivendra** [comment]
Hi! That’s great, welcome :)

The instructions above should be a good place to start, but feel free to as any questions you have here (or on twitter @vvendra if you prefer).

**Comment by codersanjeev** [comment]
Hi, @quinntrang are you still working on this issue?

**Comment by vinivendra** [comment]
Welcome @codersanjeev :)
I haven't heard from @quinntrang since then, so I think it's safe to assume they're not working on this. Feel free to get it for yourself if you want to. It's been a while, but the instructions above should still be OK. Let me know if anything seems weird for you though.

@quinntrang, if you come back later still wanting a starter bug, just let me know and I'll create a new one for you.

**Comment by codersanjeev** [comment]
@vinivendra  please review, till then, I am looking for the next good first-time issue.
