### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Aspie96** [vinivendra/Gryphon#84]
The license to this project is the Hippocratic License.

However, it previously was Apache, which requires:
> You must give any other recipients of the Work or Derivative Works a copy of this License; and

And:
> Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions.

So the contributions you received (and there are merged pull requests) are licensed to you under Apache 2.0.

Apache is a permissive license and using a proprietary license is allowed. However, only at the condition of following the terms.

For this reason, this project should still contain a copy of the Apache 2.0 license somewhere, unless the contributions are trivial or a license from all contributors to relicense under Hippocratic has been obtained.

Please also read:
- https://github.com/vcr/vcr/issues/804
- https://ethicalsource.dev/blog/adopting-an-ethical-license/

**Comment by vinivendra** [comment]
Hi @Aspie96, thanks a lot for the heads up! I hadn't noticed this. Let me look into it and I'll get back to you asap.

**Comment by vinivendra** [comment]
Alright, so let me start by saying that I'm not a lawyer, so I'll only be acting according to my best judgement here.

It looks like the license was changed in May 27th, and the only pull request that was made before that was #37 on May 26th, by @pt2121.

So, @pt2121, it looks like when you made your pull request to this project it was licensed to me under the Apache license, but I changed the project to the [Hippocratic License](https://github.com/vinivendra/Gryphon/blob/release/LICENSE.md) soon after that. Would you consent to relicense your code to me under the Hippocratic License?

**Comment by pt2121** [comment]
Thanks for asking. You have my consent ofc.

**Comment by vinivendra** [comment]
Thank you very much, and thanks @Aspie96 again for bringing this to my attention. Unless someone raises a question or concern, I’ll close this issue in a couple of days.

**Comment by Aspie96** [comment]
I am very happy about how this turned out.
This is the way to do stuff.

The issue is resolved.

**Comment by Aspie96** [comment]
Ops, sorry, I didn't notice you wanted to leave the issue open.

**Comment by vinivendra** [comment]
No problems, I just wanted to give people time to answer. I think it's OK to close this now. Thanks again, both of you.
