### ISSUE TITLE
support .xcfilelist comments

### ISSUE THREAD

**Issue by troys-code** [vinivendra/Gryphon#93]
## Reproduce steps

1. Add a comment to `gryphonInputFiles.xcfilelist`

```sh
Sources/JsTypes.swift
#Sources/MediaTypes.swift
```

2. Run the Gryphon target for your Xcode project
3. Expected: Gryphon runs successfully
  Actual: Gryphon fails with 'File not found' error

```
File not found: #Sources/MediaTypes.swift
```

## Extra info

When viewing `gryphonInputFiles.xcfilelist` in Xcode editor, the line starting with `#` is grayed out because Xcode recognizes it as a comment.

**Comment by vinivendra** [comment]
Thanks for the report, I just pushed commit 7aeaaa3da81a5a16b57f2bd1b75a46deb47ac839 that should fix this 😄

You can try it now if you want with `brew install vinivendra/gryphon/gryphon --HEAD`, or wait for the fix to be publicly released on Wednesday night.
